@base=http://cushon-api.test/api

### Create a new Investment
POST {{base}}/account/{account}/investment
Content-Type: application/json

{
    "isa_id": "uuid",
    "funds": [
        {
            "id": "uuid",
            "amount": "int"
        }
    ]
}

### Get Account Investments
GET {{base}}/account/{account}/investment
Content-Type: application/json


### Get Investment
GET {{base}}/investment/{investment}
Content-Type: application/json
